# Generated by Django 5.0.4 on 2024-04-26 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.freelancer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
        migrations.AddField(
            model_name='offer',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.proposal'),
        ),
        migrations.AddField(
            model_name='offer',
            name='required_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.requiredskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(to='job.requiredskill'),
        ),
    ]
