# Generated by Django 5.0.4 on 2024-06-05 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.freelancer'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_client', to='user.client'),
        ),
        migrations.AddField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.client'),
        ),
        migrations.AddField(
            model_name='offer',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.freelancer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_for_added_contracts', to='job.offer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.freelancer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.job'),
        ),
        migrations.AddField(
            model_name='offer',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.proposal'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(to='job.requiredskill'),
        ),
    ]
