# Generated by Django 5.0.4 on 2024-04-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project_length',
            field=models.CharField(max_length=10),
        ),
    ]
